#!/bin/bash

(
  set -e -x

  trap clean_vagrant EXIT

  clean_vagrant() {
    vagrant destroy remote -f || true
  }

  build_num=$(cat stemcell-version/number | cut -f1 -d.)

  cd bosh-src

  bundle

  cd bosh-stemcell

  cp ../../bosh-softlayer-private/.s3cfg .

  vagrant plugin install vagrant-scp

  vagrant up remote --provider=aws

  vagrant ssh -c "
    cd /bosh
    bundle
    export CANDIDATE_BUILD_NUMBER=$build_num
    export STEMCELL_BUILD_NUMBER=$build_num
    bundle exec rake stemcell:build[softlayer,hyperv,ubuntu,trusty,go,bosh-os-images,bosh-ubuntu-trusty-os-image.tgz]
  " remote

  mkdir ../../out

  vagrant scp remote:/mnt/stemcells/$IAAS/$HYPERVISOR/$OS_NAME/work/work/*.tgz ../../out/
)




