#!/usr/bin/env bash

(
set -e -x

trap clean_vagrant EXIT

clean_vagrant() {
  vagrant destroy remote -f || true
}

build_num=$(cat stemcell-version/number | cut -f1 -d.)

cd bosh-src

# todo check out correct version of bosh-src for that stemcell
# git checkout stable-${build_num}
# git submodule update --init --recursive
# git clean -fdx

cd bosh-stemcell

echo -e "\n Copy s3cfg to vagrant shared directory..."
cp ../../bosh-softlayer-private/.s3cfg .

vagrant up remote --provider=aws

vagrant ssh -c "
  cd /bosh
  bundle
  export CANDIDATE_BUILD_NUMBER=$build_num
  bundle exec rake stemcell:build[$IAAS,$HYPERVISOR,$OS_NAME,$OS_VERSION,go,bosh-os-images,bosh-$OS_NAME-$OS_VERSION-os-image.tgz]
" remote

mkdir ../../out

vagrant scp remote:/mnt/stemcells/$IAAS/$HYPERVISOR/$OS_NAME/work/work/*.tgz ../../out/

)
