#!/bin/bash

(
  set -e -x
 
  base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
  base_gopath=$( cd $base/../../../.. && pwd )

  export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

  STEMCELL_VERSION=$(cat stemcell-version/number | cut -f1 -d.)

  echo -e "\n Creating stemcell binary..."
  go build -o out/sl_stemcells github.com/maximilien/bosh-softlayer-stemcells/main

  echo -e "\n Softlayer create light stemcell..."
  out/sl_stemcells --version $STEMCELL_VERSION --stemcell-info-filename stemcell-info/stemcell-info.json light-stemcell-for-softlayer-$STEMCELL_VERSION

)