#!/bin/bash

(
  set -e

  echo -e "\n Getting VGBTG id"
  vgbtgID=`cat stemcell-info/stemcell-info.json | grep '"id":' | cut -d ":" -f2 | cut -d "," -f1`

  echo -e "\n Connecting to Softlayer"
  touch sl-config
  echo "username = $SL_USERNAME" >> sl-config
  echo "api_key = $SWIFT_API_KEY" >> sl-config
  echo "endpoint_url = " >> sl-config
  echo "timeout = 40"

  slcli --config sl-config

  echo -e "\n Tagging the VGBTG with SHIPIT"
  slcli image edit --note "SHIPIT" $vgbtgID

)
